local htmlWriter = {
}

function htmlWriter.writeHeader(fout)
    fout:write([[
<html>
    <head>
        <title>Emender Test Suite</title>
    </head>
    <body>
        <div>
          <h1>Emender Test Suite</h1>
        </div>

<ul id='all-tests'>
]])
end

function htmlWriter.writeFooter(fout)
    fout:write([[

        <div>Generated by Emender</div>
    </body>
</html>]])
end

function htmlWriter.writeOverallResults(fout, okTests, failedTests)
    fout:write("</ul>\n\n")
    fout:write("<ul id='overall_results'>\n")
    fout:write("    <li>Total:<span>" ..(okTests + failedTests).."</span></li>\n")
    fout:write("    <li>Passed:<span>" ..okTests.."</span></li>\n")
    fout:write("    <li>Failed:<span>" ..failedTests.."</span></li>\n")
    fout:write("</ul>\n")
end

function htmlWriter.writeTestName(fout, testName)
    fout:write("    <li class='test'>\n")
    fout:write("        <div>\n")
    fout:write("            <h2>" .. testName .. "</h2>\n")
    fout:write("        </div>\n")
    fout:write("        <ul>\n")
end

function htmlWriter.writeTestSummary(fout, okCnt, errorCnt)
    fout:write("        </ul>\n")
    fout:write("        <div>\n")
    fout:write("            <h3>Summary:</h3>\n")
    fout:write("            <ul>\n")
    fout:write("                <li>Total:<span>" .. (okCnt+errorCnt) .. "</span></li>\n")
    fout:write("                <li>Failed:<span>" .. errorCnt .. "</span></li>\n")
    fout:write("            </ul>\n")
    fout:write("        </div>\n")
    fout:write("    </li>\n")
end

function htmlWriter.writeTestFunctionName(fout, functionName)
    fout:write("        <li class='method'>\n")
    fout:write("            <h3>" .. functionName .. "</h3>\n")
    fout:write("            <ul>\n")
end

function htmlWriter.writeTestEnd(fout)
    fout:write("            </ul>\n")
    fout:write("        </li>\n")
end

function htmlWriter.writeTestOk(fout, message)
    local msg = message or "(unknown)"
    fout:write("                <li><span class='passed'>PASSED</span><span>" .. msg .. "</span></li>\n")
end

function htmlWriter.writeTestError(fout, message)
    local msg = message or "(unknown)"
    fout:write("                <li><span class='passed'>FAILED</span><span>" .. msg .. "</span></li>\n")
end

return htmlWriter

