=head1 NAME

emender_xml - description of the XML output from Emender

=head1 SYNOPSIS

  <report xmlns="http://emender.blackened.cz/1.0/">
    <suite name="TestManPages" result="fail">
      <info>
        <description>Verify that all manual pages are valid.</description>
        <authors>John Doe</authors>
        <emails>john@example.com</emails>
        <modified>2014-07-31</modified>
        <tags>
          <tag>Sanity</tag>
          <tag>Basic</tag>
        </tags>
      </info>
      <case name="testExistence" result="pass">
        <test result="pass">Exists: doc/man/man1/emend.pod</test>
        <test result="pass">Exists: doc/man/man3/emender.pod</test>
        <test result="pass">Exists: doc/man/man5/emender_xml.pod</test>
      </case>
      <case name="testValidity" result="fail">
        <test result="pass">Validates: doc/man/man1/emend.pod</test>
        <test result="fail">Validates: doc/man/man3/emender.pod</test>
        <test result="fail">Validates: doc/man/man5/emender_xml.pod</test>
      </case>
    </suite>
    <suite name="TestLinks" result="pass">
      <info>
        <description>Verify that all links are functional.</description>
        <authors>John Doe</authors>
        <emails>john@example.com</emails>
        <modified>2014-09-10</modified>
        <tags>
          <tag>Basic</tag>
        </tags>
      </info>
      <case name="testExternalLinks" result="pass">
        <test result="pass">Works: http://example.com/</test>
        <test result="pass">Works: http://example.org/</test>
        <test result="info">Skipped: http://localhost/</test>
        <test result="pass">Works: http://example.net/</test>
      </case>
    </suite>
  </report>

=head1 DESCRIPTION

=head2 Supported Elements

=over

=item B<report>

The B<report> element is the root element of the XML file generated by
Emender. It requires one attribute: the XML Namespace.

Attributes: an XML Namespace

Child elements: B<suite>

Parent elements: this element is a root element

The following is the formal definition of the B<report> element:

  element.report = element report {
      element.suite+
  }

=item B<suite>

The B<suite> element represents a single test file. It requires two
attributes: the B<name> attribute contains the name of the test and the
B<result> attribute contains the overall test result.

Attributes: B<name>, B<result>

Child elements: B<info>, B<case>

Parent elements: B<report>

The following is the formal definition of the B<suite> element:

  element.suite = element suite {
      attribute.name,
      attribute.result,
      element.info,
      element.case*
  }

=item B<info>

The B<info> element groups together information about the test file.

Attributes: this element has no attributes

Child elements: B<description>, B<authors>, B<emails>, B<modified>, B<tags>

Parent elements: B<suite>

The following is the formal definition of the B<info> element:

  element.info = element info {
      element.description &
      element.authors &
      element.emails &
      element.modified &
      element.tags
  }

=item B<description>

The B<description> element represents a brief description of the test file
and its purpose.

Attributes: this element has no attributes

Child elements: this element has no child elements

Parent elements: B<info>

The following is the formal definition of the B<description> element:

  element.description = element description {
      text
  }

=item B<authors>

The B<authors> element represents a comma-separated list of authors.

Attributes: this element has no attributes

Child elements: this element has no child elements

Parent elements: B<info>

The following is the formal definition of the B<authors> element:

  element.authors = element authors {
      text
  }

=item B<emails>

The B<emails> element represents a comma-separated list of emails.

Attributes: this element has no attributes

Child elements: this element has no child elements

Parent elements: B<info>

The following is the formal definition of the B<emails> element:

  element.emails = element emails {
      text
  }

=item B<modified>

The B<modified> element represents the date of last modification. It
contains the date in the B<I<YYYY>-I<MM>-I<DD>> format.

Attributes: this element has no attributes

Child elements: this element has no child elements

Parent elements: B<info>

The following is the formal definition of the B<modified> element:

  element.modified = element modified {
      xsd:date
  }

=item B<tags>

The B<tags> element groups together tags associated with the test.

Attributes: this element has no attributes

Child elements: B<tag>

Parent elements: B<info>

The following is the formal definition of the B<tags> element:

  element.tags = element tags {
      element.tag*
  }

=item B<tag>

The B<tag> element represents a single tag associated with the test.

Attributes: this element has no attributes

Child elements: this element has no child elements

Parent elements: B<tags>

The following is the formal definition of the B<tag> element:

  element.tag = element tag {
      text
  }

=item B<case>

The B<case> element represents a single test method. It requires two
attributes: the B<name> attribute contains the name of the test method and
the B<result> attribute contains the overall result of this test method.

Attributes: B<name>, B<result>

Child elements: B<test>

Parent elements: B<suite>

The following is the formal definition of the B<case> element:

  element.case = element case {
      attribute.name,
      attribute.result,
      element.test*
  }

=item B<test>

The B<test> element represents a single test function. It requires one
attribute: the B<result> attribute contains the result of this test
function.

Attributes: B<result>

Child elements: this element has no child elements

Parent elements: B<case>

The following is the formal definition of the B<test> element:

  element.test = element test {
      attribute.result,
      text*
  }

=back

=head2 Supported Attributes

=over

=item B<name>

The B<name> attribute represents the name of a test file or an individual
test method.

Allowed values: a string

Elements that have this attribute: B<suite>, B<case>

The following is the formal definition of the B<name> attribute:

  attribute.name = attribute name {
      text
  }

=item B<result>

The B<result> attribute represents the result of a test, a test method, or
an individual test function.

Allowed values: B<pass>, B<fail>, B<info>

Elements that have this attribute: B<suite>, B<case>, B<test>

The following is the formal definition of the B<result> attribute:

  attribute.result = attribute result {
      xsd:string "pass" |
      xsd:string "fail" |
      xsd:string "info"
  }

=back

=head1 SEE ALSO

B<emend>(1), B<lua>(1)

=head1 BUGS

To report a bug or submit a patch, please, file a new issue at
L<https://github.com/emender/emender/issues>.

=head1 COPYRIGHT

Copyright (C) 2014 Jaromir Hradilek

This program is free software; see the source for copying conditions. It is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

=cut
